### ISSUE TITLE
Package-level inputs are missing

### ISSUE THREAD

**Issue by herzog31** [adobe/aio-cli-plugin-app-dev#135]
**Describe the bug**
The `dev` command only considers input variables scoped to an action, but it's missing package-level input variables.

**To Reproduce**
Consider the following `app.config.yaml`:

```yaml
application:
  actions: actions
  runtimeManifest:
    packages:
      my-app:
        license: Apache-2.0
        inputs:
          VALUE_B: 'test2'
        actions:
          pdp-renderer:
            function: actions/action/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              VALUE_A: 'test1'
            annotations:
              final: true
```

1. When deploying this app, both values `VALUE_A` and `VALUE_B` are available to the action.
2. When running `aio app dev`, only `VALUE_A` is available.

**Expected behavior**
Action and package-level input variables are available to actions.

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Browser Chrome
 - Version 131
